### ISSUE TITLE
Upload SCR: Structural issue- Missing type parameter and value in payload

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#155] opened 2021-03-18 10:27 UTC
**Describe the bug**
The type is required parameter in payload whose default value is document. If we are not passing it in payload, still we are receiving 201 Created response

**To Reproduce**
Below is the complete request attached -
[Missing type parameter.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163231/Missing.type.parameter.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111611583-a2f1cd80-8802-11eb-85f3-49504a9c4304.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos Can you please check and suggest

**Comment by michael-kainos** [comment] 2021-03-19 12:52
Duplicate of https://github.com/NHSDigital/summary-care-record-api/issues/148

**Closed by michael-kainos** 2021-03-19 12:52 UTC
